@startuml

class Topic {
  id
}
note left: Topic structure is derived from its \nunique (optional) formalization\nbut carried by the Topic,\nbecause the formalization is a Symbol

Topic "1..*" --o "*" Symbol
(Topic , Symbol) . Interpretation
class Interpretation {}
note top: could be restricted to a community or domain

DecontextualizedSymbol <|-- Formalization

class Formalization {
  Formalization canonicalize()
}

Topic "1" *-- "0..1" Formalization

Topic <|-- Claim

DecontextualizedSymbol "*" --> "*" DecontextualizedSymbol
(DecontextualizedSymbol , DecontextualizedSymbol) . SymbolRelation
DecontextualizedSymbol <|-- DeclarativeSentence

SymbolRelation o--> "1" SymbolRelationType

enum SymbolRelationType {
  equivalent
  not_equivalent
  precision
}

Quote "*" -- "1" DecontextualizedSymbol
Quote "*" --* "1" Document

interface Symbol
Symbol <|-- DecontextualizedSymbol
Symbol <|-- Quote

class Quote {
  DecontextualizedSymbol detach()
}

class Document {

}
note bottom: digital objects, Agents and literals are also Topics


Claim <|-- Argument

Topic "*" <-- Claim : entities
Argument o--> "*" Claim : premises
Argument o--> "1" Claim : conclusion

Claim <|-- LogicalVariant
Claim "1" <--o LogicalVariant

DeclarativeSentence .. Claim

class LogicalVariant {
  truthvalue
  Claim baseClaim
}

class ArgumentFamily {
  Claim baseConclusion()
  Claim[] basePremises()
}

Argument "1..*" <--o ArgumentFamily
Topic <|-- ArgumentFamily

@enduml
