@startuml

class Claim {
  String* positive_sentences
  String* negation_sentences
  String generate_negation_sentence()
}

class Support {
  Claim premise
  boolean premise_affirmation
  Claim conclusion
  boolean conclusion_affirmation
}

Claim "1" <- Support: < premise 
Claim "1" <- Support: < conclusion

Claim <|-- Support

@enduml

