@startuml

class Claim {
  String sentence
  ' String negation_sentence  (must be != sentence)
}

Claim "*" <-> "*" Claim : > equivalent_to
note  "implicitly reflexive, symmetric?, transitive?" as N2
(Claim, Claim) .. N2

'(Claim, Claim) . ClaimEquivalence
'ClaimEquivalenceClass o-> "*" Claim

'ClaimEquivalence "*" -> "*" ClaimEquivalence : > negation

Claim "*" -> "*" Claim : > negation
note  "anti-reflexive, symmetric?, anti-transitive?" as N1
(Claim, Claim) .. N1

Claim o-> Claim : > supports
note "A negation B, B equivalent_to C => A negation C" as N3
'(Claim, Claim) .. N3

Claim o-> Claim : > opposes
' (Claim, Claim) .. N4


@enduml
