@startuml

class Claim {
  String* sentences
  String generate_negation_sentence()
}

class Support {
  Claim premise
  Claim conclusion
}

Claim "1" <- Support: < premise 
Claim "1" <- Support: < conclusion

Claim <|-- Support

Claim "1" -> "1" Claim : > negation
note  "anti-reflexive, symmetric" as N1
(Claim, Claim) .. N1

@enduml

